// node scripts/fonts.mjs -> src/styles/fonts.css
// Self-hosted faces from @fontsource, renamed to the family names the app already uses, and trimmed to
// the scripts we set (Latin, Latin Extended, Thai). Rerun after updating the @fontsource packages.
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCES = [
  ['@fontsource-variable/fraunces', 'opsz.css', 'Fraunces'],
  ['@fontsource-variable/fraunces', 'opsz-italic.css', 'Fraunces'],
  ['@fontsource-variable/bricolage-grotesque', 'opsz.css', 'Bricolage Grotesque'],
  ['@fontsource-variable/anuphan', 'index.css', 'Anuphan'],
  ['@fontsource-variable/noto-serif-thai', 'index.css', 'Noto Serif Thai'],
  ['@fontsource/trirong', '400.css', 'Trirong'],
  ['@fontsource/trirong', '500.css', 'Trirong'],
  ['@fontsource/trirong', '700.css', 'Trirong'],
  ['@fontsource/trirong', '400-italic.css', 'Trirong'],
  ['@fontsource/sriracha', '400.css', 'Sriracha'],
];
const KEEP = new Set(['latin', 'latin-ext', 'thai', 'vietnamese']); // vietnamese: Thích Nhất Hạnh's name
// Letters our faces do not have (Pali ṅ, Pinyin ǐ, the Greek and Cyrillic originals) come from Noto, a matched
// classic face, instead of whatever the phone happens to have. Declared first: for a letter in both, the face
// declared later wins, so Fraunces and Bricolage draw every letter they have and Noto only fills the gaps. The
// browser downloads a Noto file only when a page shows one of those letters.
const FALLBACKS = [
  ['@fontsource-variable/noto-serif', 'wght.css', 'Fraunces'],
  ['@fontsource-variable/noto-serif', 'wght-italic.css', 'Fraunces'],
  ['@fontsource-variable/noto-sans', 'wght.css', 'Bricolage Grotesque'],
];
const FALLBACK_KEEP = new Set(['latin-ext', 'greek', 'greek-ext', 'cyrillic', 'cyrillic-ext']);
// "/* noto-serif-thai-latin-wght-normal */": the subset is the last known name in the slug
const subsetOf = (block) => {
  const name = (block.match(/^\/\* ([a-z0-9-]+) \*\//) || [])[1] || '';
  const hits = [...`-${name}-`.matchAll(/-(latin-ext|latin|thai|vietnamese|cyrillic-ext|cyrillic|greek-ext|greek|math|symbols)(?=-)/g)];
  return hits.length ? hits[hits.length - 1][1] : '';
};

// a unicode-range minus some code points, range by range (U+0300-0304 without U+0304 is U+0300-0303)
const hex = (n) => n.toString(16).toUpperCase().padStart(4, '0');
const without = (range, drop) => range.split(',').map((s) => s.trim()).flatMap((tok) => {
  const m = /^U\+([0-9A-F]+)(?:-([0-9A-F]+))?$/i.exec(tok);
  if (!m) return [tok]; // a wildcard form (U+4??) stays as it is
  let lo = parseInt(m[1], 16);
  const hi = m[2] ? parseInt(m[2], 16) : lo, parts = [];
  for (const d of drop.filter((d) => d >= lo && d <= hi).sort((a, b) => a - b)) { if (d > lo) parts.push([lo, d - 1]); lo = d + 1; }
  if (lo <= hi) parts.push([lo, hi]);
  return parts.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`));
}).join(',');
if (without('U+0300-0301,U+0303-0304,U+0308-0309,U+0329', [0x304, 0x308, 0x329]) !== 'U+0300-0301,U+0303,U+0309') throw new Error('without() is wrong');

let out = '/* Generated by scripts/fonts.mjs from @fontsource. Do not edit by hand. */\n';
for (const [pkg, file, family, keep] of [...FALLBACKS.map((f) => [...f, FALLBACK_KEEP]), ...SOURCES.map((f) => [...f, KEEP])]) {
  const css = readFileSync(`node_modules/${pkg}/${file}`, 'utf8');
  // each block is "/* subset */\n@font-face {...}"
  for (const block of css.split(/(?=\/\* [a-z0-9-]+ \*\/)/)) {
    if (!keep.has(subsetOf(block.trim()))) continue;
    out += block
      .replace(/font-family: '[^']+'/, `font-family: '${family}'`)
      .replace(/url\(\.\/files\//g, `url(../../node_modules/${pkg}/files/`)
      .replace(/,\s*url\([^)]*\.woff\) format\('woff'\)/g, '') // every browser we support reads woff2
      // Fraunces offers the combining macron and diaeresis in its basic Latin file but has no mark positioning:
      // Chrome then keeps "Dōgen" in that one file by splitting ō into o and a combining macron, and the macron lands
      // on the next letter. Without them, every engine uses the real precomposed ō from the extended file.
      .replace(/(unicode-range:\s*)([^;]*)/, (_, k, r) => k + (family === 'Fraunces' ? without(r, [0x304, 0x308, 0x329]) : r))
      .trim() + '\n';
  }
}
// every range must parse: one bad token (it was "U+0303-0304-0309") makes a browser treat the face as covering every
// character, so Thai pages downloaded the Vietnamese Fraunces files before the Thai face was even asked for
for (const [, r] of out.matchAll(/unicode-range:\s*([^;]*);/g)) {
  for (const tok of r.split(',')) if (!/^\s*U\+[0-9A-F?]{1,6}(-[0-9A-F]{1,6})?\s*$/i.test(tok)) throw new Error(`bad unicode-range token "${tok}" in ${r}`);
}
writeFileSync('src/styles/fonts.css', out);
console.log('wrote src/styles/fonts.css', (out.match(/@font-face/g) || []).length, 'faces');
